name: Metrics

on:
  push:
    branches: ["main"]
    paths: ["README.md"]
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write   # <-- necesario para poder commitear/pushear

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          user: pepegoterass
          token: ${{ secrets.METRICS_TOKEN }}   # PAT classic
          filename: metrics.svg
          template: classic
          config_timezone: America/Mexico_City
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: Commit & push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # usa el token del workflow con permisos de write
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add metrics.svg
          git commit -m "chore: update metrics" || exit 0
          git push
